apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      #It's a common standard to have port and targetPort to have same same
      port: 27017 
      targetPort: 27017 
