apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      #It's a common standard to have port and targetPort to have same same
      port: 3000
      targetPort: 3000
      nodePort: 30100
